version: "3.8"
services: 
  php:
    build: ./docker/php
    volumes: 
      - ./laravel_app:/work
      - vendor-store:/work/vendor
      - node_modules-store:/work/node_modules
    depends_on: 
      - mysql
  
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./laravel_app:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    depends_on: 
      - php

  mysql:
    build: ./docker/mysql
    volumes: 
      - db-volume:/var/lib/mysql

volumes: 
  vendor-store:
  node_modules-store:
  db-volume: